### ISSUE TITLE
Bug: sbb-ghettobox-container not working since version 8.3.X

### ISSUE THREAD

**Issue by jeripeierSBB** [SchweizerischeBundesbahnen/sbb-angular#166] opened 2019-09-12 15:05 UTC
**Describe the bug**
When including sbb-ghettobox-container in an html template, the app doesn't start anymore and the following error is displayed:
``main.ts:12 TypeError: Class constructor BasePortalOutlet cannot be invoked without 'new'
    at new GhettoboxContainerComponent (sbb-esta-angular-public-ghettobox.js:732)
    at createClass (core.js:27853)
    at createDirectiveInstance (core.js:27673)
    at createViewNodes (core.js:38309)
    at callViewAction (core.js:38759)
    at execComponentViewsAction (core.js:38664)
    at createViewNodes (core.js:38338)
    at createRootView (core.js:38181)
    at callWithDebugContext (core.js:39710)
    at Object.debugCreateRootView [as createRootView] (core.js:38947)``

With Version 8.0.2of sbb-angular sbb-ghettobox-container did work

**To Reproduce**
Because stackblitz doesn't know the new sbb-angular version, it's not possible to provide a stackblitz demo.

**Expected behavior**
No error when using sbb-ghettobox-container

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Comment by kyubisation** [comment] 2019-09-13 16:29
I was unable to reproduce it locally or with StackBlitz: https://stackblitz.com/edit/angular-sbb-2axb69?file=package.json (Updated to newest version)
Which version of the CDK are you using?

**Comment by jeripeierSBB** [comment] 2019-09-16 07:46
I was using version 8.0.2. Now I'm using version 8.2.0 and it works again. Sorry, it was not clear to me, that version of the cdk affects sbb-angular version

**Comment by kyubisation** [comment] 2019-09-16 09:08
While it should not, the CDK can of course also have bugs that are fixed with later versions. Our focus is supporting latest versions, while giving best effort to earlier versions.
Is it ok to close this issue?

**Comment by jeripeierSBB** [comment] 2019-09-16 12:02
yes :-) thank you

**Closed** 2019-09-16 16:23 UTC
Labels: bug, comp: public, prio2: high
